/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package capainterfaz;

import capanegocio.Articulo;
import capanegocio.Categoria;
import capanegocio.Cliente;
import capanegocio.Empleado;
import capanegocio.Hotel;
import capanegocio.Persona;
import capanegocio.TipoAlerta;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;


/**
 *
 * @author zapat
 */
public class JFrameAdmin extends javax.swing.JFrame {

    Hotel hotel;
    String admin;
    private DefaultTableModel modelTablaClientes;
    private DefaultTableModel modelTablaArticulos;
    private DefaultTableModel modelTablaEmpleados;
    private int mesInicio;
    private List<Integer> dias;
    private String[] meses;


    
    public JFrameAdmin(Hotel hotel, String admin) {
        this.hotel = hotel;
        this.admin = admin;
        this.meses = new String[12];
        initComponents();
        obtenerDatos();
    }
    private void llenaDias(){
        jTableVisualizarReserva.setModel(hotel.generarModeloTabla("102"));
        jTableVisualizarReserva.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        TableColumnModel column = jTableVisualizarReserva.getColumnModel();
        column.getColumn(0).setPreferredWidth(75);
        column.getColumn(1).setPreferredWidth(665);
    }
    private void obtenerDatos(){
        llenaDias();
        jCBHabitacionReserva.setModel(hotel.getHabitaciones());
        meses[0]="Enero";
        meses[1]= "Febrero";
        meses[2]= "Marzo";
        meses[3]= "Abril";
        meses[4]= "Mayo";
        meses[5]= "Junio";
        meses[6]= "Julio";
        meses[7]= "Agosto";
        meses[8]= "Septiembre";
        meses[9]= "Octubre";
        meses[10]= "Noviembre";
        meses[11]="Diciembre";
        modelTablaClientes = new DefaultTableModel(
        new Object[]{"Nombre", "Apellido", "Cedula"}, 0);
        jTableClientes.setModel(hotel.visualizarClientes(modelTablaClientes));
        
        modelTablaArticulos= new DefaultTableModel(
        new Object[]{"Nombre", "Categoria", "Cantidad", "Prioridad"}, 0);
        jTableArticulo.setModel(hotel.visualizarArticulos(modelTablaArticulos));
        
        DefaultComboBoxModel<String> mesCombo = new DefaultComboBoxModel<>();
        for (int i = 0; i < 12; i++) {
            mesCombo.addElement(meses[i]);
        }
        jCBMesEntradaReserva.setModel(mesCombo);
        
        modelTablaEmpleados= new DefaultTableModel(
        new Object[]{"Nombre", "Apellido", "Cedula","Cargo"}, 0);
        jTableEmpleados.setModel(hotel.visualizarEmpleado(modelTablaEmpleados));
        
    }

    private JFrameAdmin() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAgregarCliente = new javax.swing.JButton();
        txtNombreCliente = new javax.swing.JTextField();
        txtApellidoCliente = new javax.swing.JTextField();
        txtCedulaCliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        txtCedulaBuscarCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnBuscarCliente = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnAgregarEmpleado = new javax.swing.JButton();
        txtNombreEmpleado = new javax.swing.JTextField();
        txtApellidoEmpleado = new javax.swing.JTextField();
        txtCedulaEmpleado = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableEmpleados = new javax.swing.JTable();
        txtCedulaBuscarEmpleado = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnBuscarEmpleado = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jCBCargoEmpleado = new javax.swing.JComboBox<>();
        btnAgregarEmpleado1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnAgregarArticulo = new javax.swing.JButton();
        txtNombreArticulo = new javax.swing.JTextField();
        txtCantidadArticulo = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableArticulo = new javax.swing.JTable();
        txtNombreArticuloBuscar = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btnBuscarArticuloAdmin = new javax.swing.JButton();
        jCBCategoriaArticulo = new javax.swing.JComboBox<>();
        btnAgregarArticulo1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnAsignarRecepcion = new javax.swing.JButton();
        txtNombreEmpleadoAsignarTarea = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableVisualizarAsignacion = new javax.swing.JTable();
        txtNombreAsignarTareaConserje = new javax.swing.JTextField();
        btnAsignarConserje = new javax.swing.JButton();
        jCBTareaRecepcion = new javax.swing.JComboBox<>();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jCBTareaConserje = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtNombreReserva = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jCBMesEntradaReserva = new javax.swing.JComboBox<>();
        jCBDiaEntradaReserva = new javax.swing.JComboBox<>();
        jCBMesSalidaReserva = new javax.swing.JComboBox<>();
        jCBDiaSalidaReserva = new javax.swing.JComboBox<>();
        jCBHabitacionReserva = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        txtCedulaReserva = new javax.swing.JTextField();
        btnBuscarReserva = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableVisualizarReserva = new javax.swing.JTable();
        btnConfirmarReserva = new javax.swing.JButton();
        btnAgregarCliente1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ADMINISTRADOR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 430, 60));

        jTabbedPane.setBackground(new java.awt.Color(198, 212, 225));

        jPanel2.setBackground(new java.awt.Color(201, 223, 232));

        jLabel26.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("+ Agregar Cliente");

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 1, 13)); // NOI18N
        jLabel3.setText("Nombre ");

        jLabel4.setFont(new java.awt.Font("Lucida Bright", 1, 13)); // NOI18N
        jLabel4.setText("Apellido ");

        jLabel5.setFont(new java.awt.Font("Lucida Bright", 1, 13)); // NOI18N
        jLabel5.setText("Cédula");

        btnAgregarCliente.setBackground(new java.awt.Color(0, 102, 204));
        btnAgregarCliente.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        btnAgregarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarCliente.setText("AGREGAR");
        btnAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarClienteActionPerformed(evt);
            }
        });

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Cédula", "Eliminar", "Modificar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableClientes);
        if (jTableClientes.getColumnModel().getColumnCount() > 0) {
            jTableClientes.getColumnModel().getColumn(0).setResizable(false);
            jTableClientes.getColumnModel().getColumn(1).setResizable(false);
            jTableClientes.getColumnModel().getColumn(2).setHeaderValue("Cédula");
            jTableClientes.getColumnModel().getColumn(3).setHeaderValue("Eliminar");
            jTableClientes.getColumnModel().getColumn(4).setHeaderValue("Modificar");
        }

        txtCedulaBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaBuscarClienteActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Ingrese el númeo de cédula: ");

        btnBuscarCliente.setBackground(new java.awt.Color(0, 102, 102));
        btnBuscarCliente.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        btnBuscarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarCliente.setText("BUSCAR");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 153, 153));
        btnEliminar.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("ELIMINAR SELECCINADO");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(114, 114, 114)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtApellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(118, 118, 118)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCedulaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                        .addComponent(btnAgregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel6)
                                .addGap(31, 31, 31)
                                .addComponent(txtCedulaBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(btnBuscarCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEliminar)
                                .addGap(59, 59, 59))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1034, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCedulaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnAgregarCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCedulaBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCliente)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        jTabbedPane.addTab("Cliente", jPanel2);

        jPanel3.setBackground(new java.awt.Color(196, 178, 209));

        jLabel27.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 102, 102));
        jLabel27.setText("+ Agregar Empleado");

        jLabel7.setFont(new java.awt.Font("Lucida Bright", 1, 13)); // NOI18N
        jLabel7.setText("Nombre ");

        jLabel8.setFont(new java.awt.Font("Lucida Bright", 1, 13)); // NOI18N
        jLabel8.setText("Apellido ");

        jLabel9.setFont(new java.awt.Font("Lucida Bright", 1, 13)); // NOI18N
        jLabel9.setText("Cédula");

        btnAgregarEmpleado.setBackground(new java.awt.Color(0, 102, 204));
        btnAgregarEmpleado.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        btnAgregarEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarEmpleado.setText("AGREGAR");
        btnAgregarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEmpleadoActionPerformed(evt);
            }
        });

        jTableEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Cédula", "Cargo", "Eliminar", "Modificar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableEmpleados);
        if (jTableEmpleados.getColumnModel().getColumnCount() > 0) {
            jTableEmpleados.getColumnModel().getColumn(0).setResizable(false);
            jTableEmpleados.getColumnModel().getColumn(1).setResizable(false);
            jTableEmpleados.getColumnModel().getColumn(2).setHeaderValue("Cédula");
            jTableEmpleados.getColumnModel().getColumn(4).setHeaderValue("Eliminar");
            jTableEmpleados.getColumnModel().getColumn(5).setHeaderValue("Modificar");
        }

        txtCedulaBuscarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaBuscarEmpleadoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Ingrese el númeo de cédula: ");

        btnBuscarEmpleado.setBackground(new java.awt.Color(0, 102, 102));
        btnBuscarEmpleado.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        btnBuscarEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarEmpleado.setText("BUSCAR");
        btnBuscarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEmpleadoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel11.setText("Cargo");

        jCBCargoEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RECEPCION", "CONSERJE" }));

        btnAgregarEmpleado1.setBackground(new java.awt.Color(255, 153, 153));
        btnAgregarEmpleado1.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        btnAgregarEmpleado1.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarEmpleado1.setText("ELIMINAR SELECCINADO");
        btnAgregarEmpleado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEmpleado1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(txtNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(80, 80, 80)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(txtApellidoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(80, 80, 80)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCedulaEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(80, 80, 80)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jCBCargoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAgregarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jSeparator2)
                                .addGap(395, 395, 395))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel10)
                                .addGap(31, 31, 31)
                                .addComponent(txtCedulaBuscarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(btnBuscarEmpleado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAgregarEmpleado1)
                                .addGap(8, 8, 8)))
                        .addContainerGap(83, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCedulaEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBCargoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnAgregarEmpleado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCedulaBuscarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarEmpleado)
                    .addComponent(btnAgregarEmpleado1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        jTabbedPane.addTab("Empleado", jPanel3);

        jPanel4.setBackground(new java.awt.Color(188, 209, 177));

        jLabel28.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(102, 102, 102));
        jLabel28.setText("+ Agregar Articulo");

        jLabel12.setFont(new java.awt.Font("Lucida Bright", 1, 13)); // NOI18N
        jLabel12.setText("Nombre ");

        jLabel13.setFont(new java.awt.Font("Lucida Bright", 1, 13)); // NOI18N
        jLabel13.setText("Categoria");

        jLabel14.setFont(new java.awt.Font("Lucida Bright", 1, 13)); // NOI18N
        jLabel14.setText("Cantidad");

        btnAgregarArticulo.setBackground(new java.awt.Color(0, 102, 204));
        btnAgregarArticulo.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        btnAgregarArticulo.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarArticulo.setText("AGREGAR");
        btnAgregarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarArticuloActionPerformed(evt);
            }
        });

        txtCantidadArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadArticuloActionPerformed(evt);
            }
        });

        jTableArticulo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Categoria", "Cantidad", "Alerta", "Eliminar", "Modificar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableArticulo);
        if (jTableArticulo.getColumnModel().getColumnCount() > 0) {
            jTableArticulo.getColumnModel().getColumn(0).setResizable(false);
            jTableArticulo.getColumnModel().getColumn(1).setResizable(false);
            jTableArticulo.getColumnModel().getColumn(2).setHeaderValue("Cédula");
            jTableArticulo.getColumnModel().getColumn(4).setHeaderValue("Eliminar");
            jTableArticulo.getColumnModel().getColumn(5).setHeaderValue("Modificar");
        }

        txtNombreArticuloBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreArticuloBuscarActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Nombre");

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        btnBuscarArticuloAdmin.setBackground(new java.awt.Color(0, 102, 102));
        btnBuscarArticuloAdmin.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        btnBuscarArticuloAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarArticuloAdmin.setText("BUSCAR");
        btnBuscarArticuloAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarArticuloAdminActionPerformed(evt);
            }
        });

        jCBCategoriaArticulo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACCESORIO_BANIO", "LIMPIEZA", "ROPA_CAMA" }));

        btnAgregarArticulo1.setBackground(new java.awt.Color(255, 153, 153));
        btnAgregarArticulo1.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        btnAgregarArticulo1.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarArticulo1.setText("ELIMINAR SELECCINADO");
        btnAgregarArticulo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarArticulo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1013, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(txtNombreArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(80, 80, 80)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jCBCategoriaArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(80, 80, 80)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(txtCantidadArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(128, 128, 128)
                                        .addComponent(btnAgregarArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel14)))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 996, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(66, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel15)
                        .addGap(31, 31, 31)
                        .addComponent(txtNombreArticuloBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(btnBuscarArticuloAdmin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregarArticulo1)
                        .addGap(148, 148, 148))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel28)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBCategoriaArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtNombreArticuloBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarArticuloAdmin)
                    .addComponent(btnAgregarArticulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        jTabbedPane.addTab("Articulo", jPanel4);

        jPanel5.setBackground(new java.awt.Color(230, 239, 204));

        jLabel29.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(102, 102, 102));
        jLabel29.setText("+ Asignar Tarea Recepción");

        jLabel17.setFont(new java.awt.Font("Lucida Bright", 1, 13)); // NOI18N
        jLabel17.setText("Nombre Empleado");

        jLabel18.setFont(new java.awt.Font("Lucida Bright", 1, 13)); // NOI18N
        jLabel18.setText("Tarea");

        btnAsignarRecepcion.setBackground(new java.awt.Color(0, 102, 204));
        btnAsignarRecepcion.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        btnAsignarRecepcion.setForeground(new java.awt.Color(255, 255, 255));
        btnAsignarRecepcion.setText("ASIGNAR");
        btnAsignarRecepcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarRecepcionActionPerformed(evt);
            }
        });

        jTableVisualizarAsignacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Nombre Empleado", "Tarea Asignada", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTableVisualizarAsignacion);
        if (jTableVisualizarAsignacion.getColumnModel().getColumnCount() > 0) {
            jTableVisualizarAsignacion.getColumnModel().getColumn(0).setResizable(false);
            jTableVisualizarAsignacion.getColumnModel().getColumn(1).setResizable(false);
            jTableVisualizarAsignacion.getColumnModel().getColumn(2).setResizable(false);
        }

        txtNombreAsignarTareaConserje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreAsignarTareaConserjeActionPerformed(evt);
            }
        });

        btnAsignarConserje.setBackground(new java.awt.Color(0, 102, 102));
        btnAsignarConserje.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        btnAsignarConserje.setForeground(new java.awt.Color(255, 255, 255));
        btnAsignarConserje.setText("ASIGNAR");

        jCBTareaRecepcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Atención al cliente y registro de visitantes", "Gestión de correspondencia y llamadas telefónicas", "Organización de agendas y citas de gerentes", "Gestión de solicitudes de acceso a áreas restringidas", "Coordinación de salas de reuniones y eventos." }));
        jCBTareaRecepcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBTareaRecepcionActionPerformed(evt);
            }
        });

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));

        jLabel19.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("+ Asignar Tarea Conserje");

        jLabel20.setFont(new java.awt.Font("Lucida Bright", 1, 13)); // NOI18N
        jLabel20.setText("Nombre Empleado");

        jLabel21.setFont(new java.awt.Font("Lucida Bright", 1, 13)); // NOI18N
        jLabel21.setText("Tarea");

        jCBTareaConserje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Limpieza de oficinas del primer piso", "Mantenimiento de áreas comunes (pasillos y baños)", "Gestión de residuos y reciclaje", "Limpieza de la cafetería y áreas de descanso", "Supervisión de suministros de limpieza y reparaciones menores" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19)
                            .addComponent(btnAsignarConserje, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator5)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(txtNombreEmpleadoAsignarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(114, 114, 114)
                                .addComponent(btnAsignarRecepcion))
                            .addComponent(jLabel21)
                            .addComponent(txtNombreAsignarTareaConserje, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBTareaRecepcion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCBTareaConserje, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel29)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreEmpleadoAsignarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAsignarRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBTareaRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreAsignarTareaConserje, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAsignarConserje, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(jCBTareaConserje, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane.addTab("Asignación Tarea", jPanel5);

        jPanel6.setBackground(new java.awt.Color(218, 219, 249));

        jLabel22.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("ENTRADA");

        jLabel23.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("SALIDA");

        jLabel24.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel24.setText("Nombre del Cliente");

        txtNombreReserva.setEnabled(false);

        jLabel25.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jLabel25.setText("Elige el Mes");

        jLabel30.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jLabel30.setText("Día de Ingreso");

        jLabel31.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jLabel31.setText("Elija el Mes");

        jLabel32.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jLabel32.setText("Día de Salida");

        jLabel33.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jLabel33.setText("Habitación");

        jCBMesEntradaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBMesEntradaReservaActionPerformed(evt);
            }
        });

        jCBDiaEntradaReserva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jCBDiaEntradaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBDiaEntradaReservaActionPerformed(evt);
            }
        });

        jCBMesSalidaReserva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero" }));
        jCBMesSalidaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBMesSalidaReservaActionPerformed(evt);
            }
        });

        jCBDiaSalidaReserva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jCBHabitacionReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBHabitacionReservaActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel34.setText("Número de Cédula");

        btnBuscarReserva.setBackground(new java.awt.Color(0, 102, 102));
        btnBuscarReserva.setFont(new java.awt.Font("Lucida Bright", 1, 16)); // NOI18N
        btnBuscarReserva.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarReserva.setText("Buscar");
        btnBuscarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarReservaActionPerformed(evt);
            }
        });

        jTableVisualizarReserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(jTableVisualizarReserva);

        btnConfirmarReserva.setBackground(new java.awt.Color(204, 0, 153));
        btnConfirmarReserva.setFont(new java.awt.Font("Lucida Bright", 1, 16)); // NOI18N
        btnConfirmarReserva.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmarReserva.setText("Confirmar Reserva");
        btnConfirmarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarReservaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(txtNombreReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(126, 126, 126)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(txtCedulaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(101, 101, 101)
                                        .addComponent(btnBuscarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel34)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jCBMesEntradaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(138, 138, 138)
                                        .addComponent(jCBDiaEntradaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel22)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addGap(123, 123, 123)
                                        .addComponent(jLabel30)))
                                .addGap(118, 118, 118)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel31)
                                            .addComponent(jCBMesSalidaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(120, 120, 120)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel32)
                                            .addComponent(jCBDiaSalidaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(108, 108, 108)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCBHabitacionReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel33)))))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(455, 455, 455)
                        .addComponent(btnConfirmarReserva)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCedulaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarReserva))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBMesEntradaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBDiaEntradaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBMesSalidaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBDiaSalidaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBHabitacionReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConfirmarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Reserva", jPanel6);

        getContentPane().add(jTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 1120, 530));

        btnAgregarCliente1.setBackground(new java.awt.Color(255, 0, 0));
        btnAgregarCliente1.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        btnAgregarCliente1.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarCliente1.setText("Cerrar Sesion");
        btnAgregarCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCliente1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 150, 36));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClienteActionPerformed
        String nombre = txtNombreCliente.getText();
        String apellido = txtApellidoCliente.getText();
        String cedula = txtCedulaCliente.getText();
        Cliente cliente = new Cliente(cedula,nombre,apellido);
        if(nombre.isEmpty()||apellido.isEmpty()||cedula.isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese la informacion en todos los espacios", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            hotel.agregarCliente(cliente);
            txtCedulaCliente.setText("");
            txtApellidoCliente.setText("");
            txtNombreCliente.setText("");
            obtenerDatos();
        }
    }//GEN-LAST:event_btnAgregarClienteActionPerformed

    private void txtCedulaBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaBuscarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaBuscarClienteActionPerformed

    private void btnAgregarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEmpleadoActionPerformed
        String nombre = txtNombreEmpleado.getText();
        String apellido = txtApellidoEmpleado.getText();
        String cedula = txtCedulaEmpleado.getText();
        String cargo = jCBCargoEmpleado.getSelectedItem().toString();
        if(nombre.isEmpty()||apellido.isEmpty()||cedula.isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese la informacion en todos los espacios", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            hotel.agregarEmpleado(cedula,nombre,apellido,cargo);
            obtenerDatos();
            txtNombreEmpleado.setText("");
            txtApellidoEmpleado.setText("");
            txtCedulaEmpleado.setText("");
        }
    }//GEN-LAST:event_btnAgregarEmpleadoActionPerformed

    private void txtCedulaBuscarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaBuscarEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaBuscarEmpleadoActionPerformed

    private void btnAgregarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarArticuloActionPerformed
        String nombre =  txtNombreArticulo.getText();
        String categoria = jCBCategoriaArticulo.getSelectedItem().toString();
        int cantidad;
        try{
            cantidad = Integer.parseInt(txtCantidadArticulo.getText());
        }catch(Exception e){JOptionPane.showMessageDialog(null, "Ingrese numeros en cantidad!!", "Error", JOptionPane.ERROR_MESSAGE);return;}
        if(nombre.isEmpty()||cantidad < 1)
            JOptionPane.showMessageDialog(null, "Ingrese la informacion en todos los espacios o no ingrese numeros negativos", "Error", JOptionPane.ERROR_MESSAGE);
        else{
            System.out.println(nombre);
            System.out.println(categoria);
            System.out.println(cantidad);
            hotel.agregarArticulo(nombre, 0, categoria, cantidad);
            obtenerDatos();
        }

    }//GEN-LAST:event_btnAgregarArticuloActionPerformed

    private void txtNombreArticuloBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreArticuloBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreArticuloBuscarActionPerformed

    private void btnAsignarRecepcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarRecepcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAsignarRecepcionActionPerformed

    private void txtNombreAsignarTareaConserjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreAsignarTareaConserjeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreAsignarTareaConserjeActionPerformed

    private void jCBTareaRecepcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTareaRecepcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBTareaRecepcionActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        Cliente cliente = hotel.buscarCliente(txtCedulaBuscarCliente.getText());
        if(cliente == null)
            JOptionPane.showMessageDialog(null, "No existe ese cliente", "Error", JOptionPane.ERROR_MESSAGE);
        else{
            JOptionPane.showMessageDialog(null,"Nombre: "+cliente.getNombre()+"\nApellido: "+cliente.getApellido()+"\nCedula: "+cliente.getCedula());
            txtCedulaBuscarCliente.setText("");
        }
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnAgregarCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCliente1ActionPerformed
        new Inicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAgregarCliente1ActionPerformed

    private void jCBMesEntradaReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBMesEntradaReservaActionPerformed
        if (jCBMesEntradaReserva.getSelectedItem() == null) {
            return; 
        }
        String mes = jCBMesEntradaReserva.getSelectedItem().toString();
        mesInicio = hotel.mesInt(mes);

        dias = hotel.getDias();
        jCBDiaEntradaReserva.removeAllItems();
        DefaultComboBoxModel<String> diaCombo = new DefaultComboBoxModel<>();
        for (int i = 1; i <= dias.get(mesInicio); i++) {
            String iAsString = String.valueOf(i);
            diaCombo.addElement(iAsString);
        }
        
        DefaultComboBoxModel<String> mesCombo = new DefaultComboBoxModel<>();
        for (int i = mesInicio; i <= 11; i++) {
            mesCombo.addElement(meses[i]);
        }
        jCBMesSalidaReserva.setModel(mesCombo);
        jCBDiaEntradaReserva.setModel(diaCombo);

    }//GEN-LAST:event_jCBMesEntradaReservaActionPerformed

    private void jCBDiaEntradaReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBDiaEntradaReservaActionPerformed
        if (jCBMesSalidaReserva.getSelectedItem() == null || jCBDiaEntradaReserva.getSelectedItem() == null) {
            return;     
        }
        String mes = jCBMesSalidaReserva.getSelectedItem().toString();
        mesInicio = hotel.mesInt(mes);
        dias = hotel.getDias();
        jCBDiaSalidaReserva.removeAllItems();
        int diaSeleccionado = Integer.parseInt(jCBDiaEntradaReserva.getSelectedItem().toString())+1;
        DefaultComboBoxModel<String> diaCombo = new DefaultComboBoxModel<>();

        for (int i = diaSeleccionado; i <= dias.get(mesInicio); i++) {
            diaCombo.addElement(String.valueOf(i));
        }
        jCBDiaSalidaReserva.setModel(diaCombo);
    }//GEN-LAST:event_jCBDiaEntradaReservaActionPerformed

    private void jCBMesSalidaReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBMesSalidaReservaActionPerformed
        dias = hotel.getDias();
        jCBDiaSalidaReserva.removeAllItems();
        DefaultComboBoxModel<String> diaCombo = new DefaultComboBoxModel<>();
        for (int i = 1; i <= dias.get(mesInicio); i++) {   
            String iAsString = String.valueOf(i);
            diaCombo.addElement(iAsString);
        }
        jCBDiaSalidaReserva.setModel(diaCombo);
    }//GEN-LAST:event_jCBMesSalidaReservaActionPerformed

    private void jCBHabitacionReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBHabitacionReservaActionPerformed
        jTableVisualizarReserva.setModel(hotel.generarModeloTabla(jCBHabitacionReserva.getSelectedItem().toString()));
        jTableVisualizarReserva.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        TableColumnModel column = jTableVisualizarReserva.getColumnModel();
        column.getColumn(0).setPreferredWidth(75);
        column.getColumn(1).setPreferredWidth(665);
    }//GEN-LAST:event_jCBHabitacionReservaActionPerformed

    private void btnBuscarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarReservaActionPerformed
        String cedula = txtCedulaReserva.getText();
        try{
            String nombre = hotel.buscarCliente(cedula).getNombre();
            txtNombreReserva.setText(nombre);
        }catch(Exception e){
            txtNombreReserva.setText("");
            JOptionPane.showMessageDialog(this, "No se encontro el cliente" , "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println("Error "+e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarReservaActionPerformed

    private void btnConfirmarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarReservaActionPerformed
        String nombre = txtNombreReserva.getText();
        String mesInicio = jCBMesEntradaReserva.getSelectedItem().toString();
        String habitacion = jCBHabitacionReserva.getSelectedItem().toString();
        int diaInicio = Integer.parseInt(jCBDiaEntradaReserva.getSelectedItem().toString());
        String mesFin = jCBMesSalidaReserva.getSelectedItem().toString();
        int diaFin = Integer.parseInt(jCBDiaSalidaReserva.getSelectedItem().toString());
        if(diaInicio == diaFin && mesFin.equals(mesInicio)){
            JOptionPane.showMessageDialog(this, "No se puede tener el reservar y salir el mismo dia", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            if(nombre.equals("") || nombre.equals(" ")){
                JOptionPane.showMessageDialog(this, "Identifique al cliente primero", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            hotel.modificarDisponibilidad(habitacion,mesInicio, diaInicio, mesFin, diaFin,true,nombre);
            llenaDias();
            jCBHabitacionReserva.setSelectedIndex(0);
        }
    }//GEN-LAST:event_btnConfirmarReservaActionPerformed

    private void btnBuscarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEmpleadoActionPerformed
        Empleado empleado = hotel.buscarEmpleado(txtCedulaBuscarEmpleado.getText());
        if(empleado == null)
            JOptionPane.showMessageDialog(null, "No existe ese cliente", "Error", JOptionPane.ERROR_MESSAGE);
        else{
            JOptionPane.showMessageDialog(null,"Nombre: "+empleado.getNombre()+"\nApellido: "+empleado.getApellido()+"\nCedula: "+empleado.getCedula());
            txtCedulaBuscarEmpleado.setText("");
        }
    }//GEN-LAST:event_btnBuscarEmpleadoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int num = jTableClientes.getSelectedRow();
        String cedula = modelTablaClientes.getValueAt(num, 2).toString();
        hotel.eliminarCliente(cedula);
        obtenerDatos();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAgregarEmpleado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEmpleado1ActionPerformed
        int num = jTableEmpleados.getSelectedRow();
        String cedula = modelTablaEmpleados.getValueAt(num, 2).toString();
        hotel.eliminarEmpleado(cedula);
        obtenerDatos();
    }//GEN-LAST:event_btnAgregarEmpleado1ActionPerformed

    private void btnBuscarArticuloAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarArticuloAdminActionPerformed
        String articulo = txtNombreArticuloBuscar.getText();
        if(articulo == null)
            JOptionPane.showMessageDialog(null, "No existe ese cliente", "Error", JOptionPane.ERROR_MESSAGE);
        else{
            Articulo buscado = hotel.buscarArticulo(articulo);
            JOptionPane.showMessageDialog(null,"Nombre: "+buscado.getNombre()+"\nPrecio: "+buscado.getPrecio()+"\nCategoria: "+buscado.getCategoria().toString()+"\nCantidad Disponible: "+buscado.getCantidadDisponible()+"\nPrioridad: "+buscado.getPrioridad());
        }
    }//GEN-LAST:event_btnBuscarArticuloAdminActionPerformed

    private void txtCantidadArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadArticuloActionPerformed

    }//GEN-LAST:event_txtCantidadArticuloActionPerformed

    private void btnAgregarArticulo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarArticulo1ActionPerformed
        int num = jTableArticulo.getSelectedRow();
        String nombre = jTableArticulo.getValueAt(num, 0).toString();
        hotel.eliminarArticulo(nombre);
        obtenerDatos();
    }//GEN-LAST:event_btnAgregarArticulo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarArticulo;
    private javax.swing.JButton btnAgregarArticulo1;
    private javax.swing.JButton btnAgregarCliente;
    private javax.swing.JButton btnAgregarCliente1;
    private javax.swing.JButton btnAgregarEmpleado;
    private javax.swing.JButton btnAgregarEmpleado1;
    private javax.swing.JButton btnAsignarConserje;
    private javax.swing.JButton btnAsignarRecepcion;
    private javax.swing.JButton btnBuscarArticuloAdmin;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarEmpleado;
    private javax.swing.JButton btnBuscarReserva;
    private javax.swing.JButton btnConfirmarReserva;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<String> jCBCargoEmpleado;
    private javax.swing.JComboBox<String> jCBCategoriaArticulo;
    private javax.swing.JComboBox<String> jCBDiaEntradaReserva;
    private javax.swing.JComboBox<String> jCBDiaSalidaReserva;
    private javax.swing.JComboBox<String> jCBHabitacionReserva;
    private javax.swing.JComboBox<String> jCBMesEntradaReserva;
    private javax.swing.JComboBox<String> jCBMesSalidaReserva;
    private javax.swing.JComboBox<String> jCBTareaConserje;
    private javax.swing.JComboBox<String> jCBTareaRecepcion;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTable jTableArticulo;
    private javax.swing.JTable jTableClientes;
    private javax.swing.JTable jTableEmpleados;
    private javax.swing.JTable jTableVisualizarAsignacion;
    private javax.swing.JTable jTableVisualizarReserva;
    private javax.swing.JTextField txtApellidoCliente;
    private javax.swing.JTextField txtApellidoEmpleado;
    private javax.swing.JTextField txtCantidadArticulo;
    private javax.swing.JTextField txtCedulaBuscarCliente;
    private javax.swing.JTextField txtCedulaBuscarEmpleado;
    private javax.swing.JTextField txtCedulaCliente;
    private javax.swing.JTextField txtCedulaEmpleado;
    private javax.swing.JTextField txtCedulaReserva;
    private javax.swing.JTextField txtNombreArticulo;
    private javax.swing.JTextField txtNombreArticuloBuscar;
    private javax.swing.JTextField txtNombreAsignarTareaConserje;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNombreEmpleado;
    private javax.swing.JTextField txtNombreEmpleadoAsignarTarea;
    private javax.swing.JTextField txtNombreReserva;
    // End of variables declaration//GEN-END:variables
}
